### ISSUE TITLE
Estudar e implementar Apache Tika

### ISSUE THREAD

**Issue by LeoFacB** [unb-mds/2023-2-Squad10#27]
### Descrição:
Estudo sobre a biblioteca Apache Tika. O Apache Tika é uma ferramenta versátil que pode ser usada para extrair metadados e conteúdo textual de uma ampla variedade de formatos de documentos, como PDFs, interesse do grupo para o projeto.

### Objetivos:

- [x] Pesquisar e familiarizar-se com a documentação oficial do Apache Tika.

- [x] Explorar exemplos de uso da biblioteca em nossa linguagem de programação preferida.

**Comment by Filipe-002** [comment]
foi implementado um conversor de pdf para txt que já está em pleno funcionamento.
