### ISSUE TITLE
Estudar e implementar Beautiful Soup

### ISSUE THREAD

**Issue by LeoFacB** [unb-mds/2023-2-Squad10#28]
### Descrição:
Propomos a implementação da biblioteca Beautiful Soup em nosso projeto. O Beautiful Soup é uma biblioteca Python que facilita a análise e extração de dados de documentos HTML e XML. Esta implementação pode ser valiosa para tarefas de raspagem de dados, análise de conteúdo da web ou processamento de dados estruturados em HTML/XML.

### Objetivos:

- [x] Integrar a biblioteca Beautiful Soup em nosso projeto Python.

- [x] Criar funções ou classes para realizar análises de HTML/XML.

- [x] Documentar as funções e métodos para que a equipe possa entender e usar a implementação.

**Comment by xGabrielCv** [comment]
**Documentação da Biblioteca Beautiful Soup**

**1.Introdução**

Beautiful Soup é uma biblioteca Python que facilita a análise e extração de dados de documentos HTML e XML. Ela é comumente usada para tarefas de raspagem de dados, análise de conteúdo da web e processamento de dados estruturados em HTML/XML.

**2. Instalação**

Para usar o Beautiful Soup, você primeiro precisa instalá-lo. Você pode fazer isso usando o pip:


`pip install beautifulsoup4`


**3.Uso Básico**

 
Importe a biblioteca Beautiful Soup e, se necessário, o módulo `requests` para obter o conteúdo da web.


```
from bs4 import BeautifulSoup
import requests
```


Carregue o conteúdo HTML/XML que você deseja analisar:


```
#Exemplo de carregamento de conteúdo de uma página da web
url = 'https://www.exemplo.com'
response = requests.get(url)
html = response.text
```


Crie um objeto Beautiful Soup para analisar o conteúdo:


`soup = BeautifulSoup(html, 'html.parser')`


Métodos e Funções Comuns

Pesquisa de Tags

- `find(name, attrs, recursive, text, **kwargs)`: Encontra a primeira ocorrência da tag especificada com os atributos e/ou texto correspondentes.
- `find_all(name, attrs, recursive, text, **kwargs)`: Encontra todas as ocorrências da tag especificada com os atributos e/ou texto correspondentes.
- `select(selector)`: Seleciona elementos usando seletores CSS.

Navegação no Documento

- `parent`: Retorna o elemento pai.
- `find_next_sibling(name, attrs, text)`: Encontra o próximo irmão da tag atual com os atributos e/ou texto correspondentes.
- `find_previous_sibling(name, attrs, text)`: Encontra o irmão anterior da tag atual com os atributos e/ou texto correspondentes.

 Acesso a Atributos

- `get(name, default)`: Retorna o valor do atributo especificado. Se não encontrado, retorna o valor padrão.

Manipulação de Conteúdo

- `string`: Acessa o conteúdo de texto da tag.
- `insert()`: Insere um novo elemento ou texto em uma tag.

 Iteração

- `children`: Itera sobre os filhos diretos de uma tag.
- `descendants`: Itera sobre todos os descendentes de uma tag.

 Modificação do Documento

- `replace_with()`: Substitui uma tag por outra.
- `decompose()`: Remove uma tag do documento.

Exemplo de Uso

Aqui está um exemplo simples de como usar o Beautiful Soup para extrair todos os links de uma página da web:


```
# Importe as bibliotecas
from bs4 import BeautifulSoup
import requests

# Carregue a página da web
url = 'https://www.exemplo.com'
response = requests.get(url)
html = response.text

# Crie um objeto Beautiful Soup
soup = BeautifulSoup(html, 'html.parser')

# Encontre todas as tags de âncora (links)
links = soup.find_all('a')

# Itere sobre os links e imprima o texto e o atributo "href"
for link in links:
    print(link.text, link.get('href'))
```


Este é um guia introdutório para o Beautiful Soup. Para um entendimento mais profundo e informações detalhadas sobre os métodos e funções, consulte a documentação oficial em [](https://www.crummy.com/software/BeautifulSoup/bs4/doc/](https://www.crummy.com/software/BeautifulSoup/bs4/doc/).
