### ISSUE TITLE
Aplicação de API no Projeto

### ISSUE THREAD

**Issue by Carlos42511** [unb-mds/2023-2-Squad10#50]
### Descrição:

Fazer a Aplicação da API 

### Objetivos:

- [x] #53
- [x] #54
- [x] Tentar entrar em contato pessoal Querido Diario

### Responsáveis:

@samuelalvess @Filipe-002 @Guilermanoo @xGabrielCv @Sunamit @Carlos42511 @LeoFacB

**Comment by Filipe-002** [comment]
após análise da API do Querido Diário, chegamos à conclusão de que não é necessário usar a API, pois o propósito do projeto nesse momento, é separar os dados dos DO e converter para um tipo de dado determinado. A API não faz isso. Estamos estudando a possibilidade de estudar Regex para separação.

**Comment by Filipe-002** [comment]
após uma pesquisa e estudos da API do Querido Diário, chegou-se a conclusão de que tal API não se mostrou útil para o nosso projeto, porém utilizaremos uma API de terceiros para a conversão dos dados para JSON.
